// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MasterAppDbContext))]
    [Migration("20260515064258_AddAgentProfileShortBio")]
    partial class AddAgentProfileShortBio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Domain.Entities.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionCategory")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionSurface")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BlockerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DismissedReason")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectiveAgentOid")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineStage")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId");

                    b.HasIndex("Source", "SourceRef");

                    b.HasIndex("Status", "DueDateUtc");

                    b.HasIndex("EffectiveAgentOid", "Status", "DueDateUtc");

                    b.HasIndex("OwnerId", "Status", "DueDateUtc");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("Domain.Entities.ActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionId", "OccurredUtc");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("Domain.Entities.AgentAssistant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentAgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssistantUserId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("ParentAgentUserId");

                    b.HasIndex("ParentAgentUserId", "Email")
                        .IsUnique();

                    b.ToTable("AgentAssistants");
                });

            modelBuilder.Entity("Domain.Entities.AgentClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUpn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("AgentUserId", "ClientUserId")
                        .IsUnique();

                    b.ToTable("AgentClients");
                });

            modelBuilder.Entity("Domain.Entities.AgentFinanceToolState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId", "ToolId")
                        .IsUnique();

                    b.ToTable("AgentFinanceToolStates");
                });

            modelBuilder.Entity("Domain.Entities.AgentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUpn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Npn")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortBio")
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentUpn");

                    b.HasIndex("AgentUserId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("AgentProfiles");
                });

            modelBuilder.Entity("Domain.Entities.AgentTrackingAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentTrackingProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanonical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("AgentTrackingProfileId", "IsCanonical");

                    b.ToTable("AgentTrackingAliases");
                });

            modelBuilder.Entity("Domain.Entities.AgentTrackingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUpn")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredEnvironment")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentUpn");

                    b.HasIndex("AgentUserId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("AgentTrackingProfiles");
                });

            modelBuilder.Entity("Domain.Entities.AgentZoomLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AgentZoomLinks");
                });

            modelBuilder.Entity("Domain.Entities.AnalyticsEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentSlug")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentTrackingProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ButtonLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DwellMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElementId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EngagedMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Environment")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fbclid")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormKey")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsBounceCandidate")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsExitPage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaAdId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaAdName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaAdSetId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaAdSetName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaCampaignId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaCampaignName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageKey")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Placement")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferrerHost")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScreenHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScreenWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScrollPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmitOutcome")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ViewportHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ViewportWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisitorId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentSlug");

                    b.HasIndex("AgentTrackingProfileId");

                    b.HasIndex("ClientEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_AnalyticsEvents_ClientEventId")
                        .HasFilter("[ClientEventId] IS NOT NULL");

                    b.HasIndex("DeviceType");

                    b.HasIndex("ElementKey");

                    b.HasIndex("EventType");

                    b.HasIndex("FormKey");

                    b.HasIndex("PageKey");

                    b.HasIndex("ReceivedUtc");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_AnalyticsEvents_SessionId_Behavior");

                    b.HasIndex("UtmCampaign");

                    b.HasIndex("UtmSource");

                    b.HasIndex("VisitorId");

                    b.HasIndex("AgentTrackingProfileId", "EventUtc");

                    b.HasIndex("ElementKey", "EventUtc");

                    b.HasIndex("Environment", "EventUtc");

                    b.HasIndex("EventType", "EventUtc");

                    b.HasIndex("PageKey", "EventUtc");

                    b.ToTable("AnalyticsEvents");
                });

            modelBuilder.Entity("Domain.Entities.Blocker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockerOwnerId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockerOwnerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockerReason")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnblockDueDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnblockDueDateUtc");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId", "Status");

                    b.ToTable("Blockers");
                });

            modelBuilder.Entity("Domain.Entities.BookkeepingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurringExpenseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecurringExpenseId");

                    b.HasIndex("OwnerUserId", "Scope", "EntryDate");

                    b.ToTable("BookkeepingEntries");
                });

            modelBuilder.Entity("Domain.Entities.ClientFinancialPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("ClientFinancialPlans");
                });

            modelBuilder.Entity("Domain.Entities.ClientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CrmLastTouch")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CrmNextDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmNextText")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmPriority")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmTags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("SignificantOtherDOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignificantOtherEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignificantOtherFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignificantOtherLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignificantOtherPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("Domain.Entities.Commitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DueDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FulfilledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LinkedActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromiseText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromisedById")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromisedByType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromisedToId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromisedToType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DueDateUtc", "Status");

                    b.HasIndex("PromisedById", "Status");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId");

                    b.ToTable("Commitments");
                });

            modelBuilder.Entity("Domain.Entities.DecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId", "CreatedUtc");

                    b.ToTable("DecisionRecords");
                });

            modelBuilder.Entity("Domain.Entities.FinanceToolState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId", "ToolId")
                        .IsUnique();

                    b.ToTable("FinanceToolStates");
                });

            modelBuilder.Entity("Domain.Entities.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("ClientUserId", "RelationshipType")
                        .IsUnique();

                    b.ToTable("HouseholdMembers");
                });

            modelBuilder.Entity("Domain.Entities.OnboardingInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("OnboardingInvites");
                });

            modelBuilder.Entity("Domain.Entities.OnboardingSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdministrativeExplanation")
                        .HasColumnType("text");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccountType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankRoutingNumber")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarrierAppointments")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CertificationTruthful")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CitizenshipStatus")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompensationAck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComplianceAck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConfidentialityAck")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriminalExplanation")
                        .HasColumnType("text");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNotes")
                        .HasColumnType("text");

                    b.Property<string>("DriverLicenseNumber")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverLicenseState")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("EOCoverage")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ElectronicSignatureAck")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ElectronicSignatureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectronicSignatureName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EligibilityDocumentsAck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactRelationship")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FederalWithholding")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HandbookAck")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasAdministrativeActions")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCertifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCriminalHistory")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasIdDocument")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasLicenseCopy")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasOtherDisclosures")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasPriorTermination")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasRegulatoryIssues")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasResume")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasSignedAgreements")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasSsnDocument")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasVoidedCheck")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InviteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LegalNameConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseNumbers")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensesHeld")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingAddress")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NonResidentStates")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NonSolicitAck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherDisclosuresExplanation")
                        .HasColumnType("text");

                    b.Property<string>("PayType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PayrollAcknowledgement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryExplanation")
                        .HasColumnType("text");

                    b.Property<string>("ResidentStateLicense")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SsnLast4")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("SsnNote")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateWithholding")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisionNotes")
                        .HasColumnType("text");

                    b.Property<string>("TaxFilingStatus")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TechnologyAck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TerminationExplanation")
                        .HasColumnType("text");

                    b.Property<string>("WorkAuthorizationStatus")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkNotes")
                        .HasColumnType("text");

                    b.Property<string>("WorkState")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteId")
                        .IsUnique();

                    b.ToTable("OnboardingSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.PlaybookExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionKey")
                        .IsUnique();

                    b.ToTable("PlaybookExecutions");
                });

            modelBuilder.Entity("Domain.Entities.ProductionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PersonalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("LeadId");

                    b.HasIndex("Status");

                    b.HasIndex("AgentUserId", "Side");

                    b.ToTable("ProductionRecords");
                });

            modelBuilder.Entity("Domain.Entities.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadName")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("AgentUserId", "LeadId");

                    b.ToTable("Proposals", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RecurringExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Scope", "IsActive");

                    b.ToTable("RecurringExpenses");
                });

            modelBuilder.Entity("Domain.Entities.UnderwritingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeadId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadName")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("ProductCode");

                    b.HasIndex("AgentUserId", "LeadId");

                    b.ToTable("UnderwritingRecords", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WebsiteLead", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentSlug")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentTrackingProfileId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CallTextConsent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fbclid")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("InterestType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MarketingEmailConsent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredContactMethod")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCtaKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePageKey")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitorId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentSlug");

                    b.HasIndex("AgentTrackingProfileId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("Email");

                    b.HasIndex("InterestType");

                    b.HasIndex("SourceCtaKey");

                    b.HasIndex("SourcePageKey");

                    b.HasIndex("UtmCampaign");

                    b.HasIndex("UtmSource");

                    b.HasIndex("AgentTrackingProfileId", "CreatedUtc");

                    b.HasIndex("Environment", "CreatedUtc");

                    b.ToTable("WebsiteLeads");
                });

            modelBuilder.Entity("Domain.Entities.WorkstationLeadProfile", b =>
                {
                    b.Property<string>("LeadId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Btc")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("CallCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallsMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CallsMonthStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CallsToday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CallsTodayDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CallsWeek")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CallsWeekStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CallsYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CallsYearStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmNotes")
                        .HasColumnType("text");

                    b.Property<long>("CrmOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrmStage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmStatus")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoanAmount")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("MortgageLender")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLeadType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("State")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("LeadId");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("Bucket");

                    b.HasIndex("Email");

                    b.HasIndex("OriginalLeadType");

                    b.HasIndex("Phone");

                    b.HasIndex("AgentUserId", "OriginalLeadType");

                    b.HasIndex("AgentUserId", "Phone");

                    b.ToTable("WorkstationLeadProfiles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AgentClient", b =>
                {
                    b.HasOne("Domain.Entities.ClientProfile", null)
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .HasPrincipalKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AgentTrackingAlias", b =>
                {
                    b.HasOne("Domain.Entities.AgentTrackingProfile", "Profile")
                        .WithMany("Aliases")
                        .HasForeignKey("AgentTrackingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Entities.BookkeepingEntry", b =>
                {
                    b.HasOne("Domain.Entities.RecurringExpense", "RecurringExpense")
                        .WithMany()
                        .HasForeignKey("RecurringExpenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecurringExpense");
                });

            modelBuilder.Entity("Domain.Entities.ClientFinancialPlan", b =>
                {
                    b.HasOne("Domain.Entities.ClientProfile", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.HouseholdMember", b =>
                {
                    b.HasOne("Domain.Entities.ClientProfile", null)
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .HasPrincipalKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.OnboardingSubmission", b =>
                {
                    b.HasOne("Domain.Entities.OnboardingInvite", "Invite")
                        .WithMany("Submissions")
                        .HasForeignKey("InviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invite");
                });

            modelBuilder.Entity("Domain.Entities.AgentTrackingProfile", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("Domain.Entities.OnboardingInvite", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
