using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations;

// The integrated migration designer/model snapshot is generated by the lead
// after all coordinated model edits are stable.
[DbContext(typeof(MasterAppDbContext))]
[Migration("20260918213500_AddFounderAiActionAuthorizations")]
public partial class AddFounderAiActionAuthorizations : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "FounderAiActionAuthorizations",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ActionDigest = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false),
                ScopeDigest = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false),
                AccountId = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                TenantId = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                UserId = table.Column<string>(type: "nvarchar(450)", maxLength: 450, nullable: false),
                SessionId = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                ConversationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                RequestId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                Environment = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                AuthorizationVersion = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                ToolName = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                CanonicalArgumentsJson = table.Column<string>(type: "nvarchar(max)", maxLength: 32768, nullable: false),
                ApprovedUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                ExpiresUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                State = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false),
                IdempotencyKey = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                ExecutionStartedUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                CompletedUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                ResultJson = table.Column<string>(type: "nvarchar(max)", maxLength: 32768, nullable: true),
                Revision = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_FounderAiActionAuthorizations", row => row.Id);
                table.ForeignKey("FK_FounderAiActionAuthorizations_MessageConversations_ConversationId",
                    row => row.ConversationId, "MessageConversations", "Id", onDelete: ReferentialAction.Cascade);
            });
        migrationBuilder.CreateIndex("IX_FounderAiActionAuthorizations_ActionDigest", "FounderAiActionAuthorizations", "ActionDigest", unique: true);
        migrationBuilder.CreateIndex("IX_FounderAiActionAuthorizations_ConversationId", "FounderAiActionAuthorizations", "ConversationId");
        migrationBuilder.CreateIndex("IX_FounderAiActionAuthorizations_ExpiresUtc", "FounderAiActionAuthorizations", "ExpiresUtc");
        migrationBuilder.CreateIndex("IX_FounderAiActionAuthorizations_UserId_RequestId", "FounderAiActionAuthorizations", new[] { "UserId", "RequestId" });
    }

    protected override void Down(MigrationBuilder migrationBuilder) =>
        migrationBuilder.DropTable("FounderAiActionAuthorizations");
}
