// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(MasterAppDbContext))]
[Migration("20260819000000_AddLegendSemanticTransitionEvidence")]
partial class AddLegendSemanticTransitionEvidence
{
}
