// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MasterAppDbContext))]
    [Migration("20260322051537_AddAgentPhoneToProfile")]
    partial class AddAgentPhoneToProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Domain.Entities.AgentAssistant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentAgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssistantUserId")
                        .IsUnique();

                    b.HasIndex("ParentAgentUserId");

                    b.HasIndex("ParentAgentUserId", "Email")
                        .IsUnique();

                    b.ToTable("AgentAssistants");
                });

            modelBuilder.Entity("Domain.Entities.AgentClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUpn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId")
                        .IsUnique();

                    b.HasIndex("AgentUserId", "ClientUserId")
                        .IsUnique();

                    b.ToTable("AgentClients");
                });

            modelBuilder.Entity("Domain.Entities.AgentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUpn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Npn")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentUpn");

                    b.HasIndex("AgentUserId")
                        .IsUnique();

                    b.ToTable("AgentProfiles");
                });

            modelBuilder.Entity("Domain.Entities.BookkeepingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurringExpenseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecurringExpenseId");

                    b.HasIndex("OwnerUserId", "Scope", "EntryDate");

                    b.ToTable("BookkeepingEntries");
                });

            modelBuilder.Entity("Domain.Entities.ClientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CrmLastTouch")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CrmNextDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmNextText")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmPriority")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmTags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignificantOtherDOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignificantOtherEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignificantOtherFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignificantOtherLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignificantOtherPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("Domain.Entities.FinanceToolState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId", "ToolId")
                        .IsUnique();

                    b.ToTable("FinanceToolStates");
                });

            modelBuilder.Entity("Domain.Entities.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("ClientUserId", "RelationshipType")
                        .IsUnique();

                    b.ToTable("HouseholdMembers");
                });

            modelBuilder.Entity("Domain.Entities.OnboardingInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("OnboardingInvites");
                });

            modelBuilder.Entity("Domain.Entities.OnboardingSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdministrativeExplanation")
                        .HasColumnType("text");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccountType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankRoutingNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarrierAppointments")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CertificationTruthful")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CitizenshipStatus")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompensationAck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComplianceAck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConfidentialityAck")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriminalExplanation")
                        .HasColumnType("text");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNotes")
                        .HasColumnType("text");

                    b.Property<string>("DriverLicenseNumber")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverLicenseState")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("EOCoverage")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ElectronicSignatureAck")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ElectronicSignatureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectronicSignatureName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EligibilityDocumentsAck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactRelationship")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FederalWithholding")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HandbookAck")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasAdministrativeActions")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCertifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCriminalHistory")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasIdDocument")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasLicenseCopy")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasOtherDisclosures")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasPriorTermination")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasRegulatoryIssues")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasResume")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasSignedAgreements")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasSsnDocument")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasVoidedCheck")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InviteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LegalNameConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseNumbers")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensesHeld")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingAddress")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NonResidentStates")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NonSolicitAck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherDisclosuresExplanation")
                        .HasColumnType("text");

                    b.Property<string>("PayType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PayrollAcknowledgement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryExplanation")
                        .HasColumnType("text");

                    b.Property<string>("ResidentStateLicense")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SsnLast4")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("SsnNote")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateWithholding")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisionNotes")
                        .HasColumnType("text");

                    b.Property<string>("TaxFilingStatus")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TechnologyAck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TerminationExplanation")
                        .HasColumnType("text");

                    b.Property<string>("WorkAuthorizationStatus")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkNotes")
                        .HasColumnType("text");

                    b.Property<string>("WorkState")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteId")
                        .IsUnique();

                    b.ToTable("OnboardingSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadName")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("AgentUserId", "LeadId");

                    b.ToTable("Proposals", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RecurringExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Scope", "IsActive");

                    b.ToTable("RecurringExpenses");
                });

            modelBuilder.Entity("Domain.Entities.UnderwritingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeadId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadName")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("ProductCode");

                    b.HasIndex("AgentUserId", "LeadId");

                    b.ToTable("UnderwritingRecords", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WorkstationLeadProfile", b =>
                {
                    b.Property<string>("LeadId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Btc")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("CallCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallsMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CallsMonthStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CallsToday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CallsTodayDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CallsWeek")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CallsWeekStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CallsYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CallsYearStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmNotes")
                        .HasColumnType("text");

                    b.Property<long>("CrmOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrmStage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmStatus")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoanAmount")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("MortgageLender")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLeadType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("LeadId");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("Bucket");

                    b.HasIndex("Email");

                    b.HasIndex("OriginalLeadType");

                    b.HasIndex("Phone");

                    b.HasIndex("AgentUserId", "OriginalLeadType");

                    b.HasIndex("AgentUserId", "Phone");

                    b.ToTable("WorkstationLeadProfiles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AgentClient", b =>
                {
                    b.HasOne("Domain.Entities.ClientProfile", null)
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .HasPrincipalKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.BookkeepingEntry", b =>
                {
                    b.HasOne("Domain.Entities.RecurringExpense", "RecurringExpense")
                        .WithMany()
                        .HasForeignKey("RecurringExpenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecurringExpense");
                });

            modelBuilder.Entity("Domain.Entities.HouseholdMember", b =>
                {
                    b.HasOne("Domain.Entities.ClientProfile", null)
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .HasPrincipalKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.OnboardingSubmission", b =>
                {
                    b.HasOne("Domain.Entities.OnboardingInvite", "Invite")
                        .WithMany("Submissions")
                        .HasForeignKey("InviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invite");
                });

            modelBuilder.Entity("Domain.Entities.OnboardingInvite", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
