using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using AgentPortal.Services;
using Domain.Entities;
using Domain.Messaging;
using Infrastructure.Messaging;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using Xunit;

namespace AgentPortal.Tests;

/// <summary>
/// Carrier tests start with an executed governed-frame fixture. They prove
/// certificate conservation, not natural-language grounding or admission.
/// </summary>
public sealed class LegendConnectScheduleCertificatePropagationTests
{
    private static readonly Guid Family = Guid.Parse("268d826a-ab84-4a53-91c6-e1b911c99a91");

    [Fact]
    public void FullCertificateSurvivesPlanAndNativeSerializationWithoutReconstruction()
    {
        var (rule, proof) = Execute(512);
        Assert.True(LegendConnectCurriculumService.TryProjectScheduleCertificates(proof, [rule], out var certificates));
        var certificate = Assert.Single(certificates);
        Assert.Equal("allocation_digest", certificate.SignatureDimension);
        Assert.Equal(proof.Values["allocation_digest"], certificate.Signature);
        Assert.Equal(512, certificate.Steps.Count);
        Assert.Equal(512L, certificate.Steps.Sum(step => step.WorkUnits));
        Assert.Equal(rule.IndependentEvidenceIdentities, certificate.IndependentEvidenceIdentities);
        Assert.Equal(rule.TransitionSignature, certificate.TransitionSignature);
        var plan = new LegendConnectResponseMeaningPlanSnapshot(
            "plan-fixture", "source-fixture", "response-fixture", "result-fixture", proof.Values,
            [], proof.EvidenceCount, false, ReasoningTransitionPath: proof.TransitionPath,
            ScheduleCertificates: certificates);
        var native = Native(proof, certificates);
        var reloadedPlan = JsonSerializer.Deserialize<LegendConnectResponseMeaningPlanSnapshot>(JsonSerializer.Serialize(plan));
        var reloadedNative = JsonSerializer.Deserialize<LegendConnectNativeInferenceSnapshot>(JsonSerializer.Serialize(native));
        Assert.NotNull(reloadedPlan);
        Assert.NotNull(reloadedNative);
        Assert.Equal(JsonSerializer.Serialize(certificates), JsonSerializer.Serialize(reloadedPlan!.ScheduleCertificates));
        Assert.Equal(JsonSerializer.Serialize(certificates), JsonSerializer.Serialize(reloadedNative!.ScheduleCertificates));
        Assert.Equal(proof.TransitionPath, reloadedNative.ReasoningTransitionPath);
    }

    [Fact]
    public void SignatureWithoutExecutableStepsOrExactRuleCannotBecomeACertificate()
    {
        var (rule, proof) = Execute(7);
        var missingSteps = proof with
        {
            EvidenceLineage = [proof.EvidenceLineage[0] with { ScheduleSteps = null }]
        };
        Assert.False(LegendConnectCurriculumService.TryProjectScheduleCertificates(missingSteps, [rule], out var none));
        Assert.Empty(none);
        Assert.False(LegendConnectCurriculumService.TryProjectScheduleCertificates(proof,
            [rule with { TransitionSignature = "unrelated-rule" }], out none));
        Assert.Empty(none);
        var wrongRole = rule with
        {
            ResultFrame = rule.ResultFrame.ToDictionary(item =>
                item.Key == "allocation_digest" ? "different_digest" : item.Key, item => item.Value)
        };
        Assert.False(LegendConnectCurriculumService.TryProjectScheduleCertificates(proof, [wrongRole], out none));
        Assert.Empty(none);
    }

    [Fact]
    public async Task NativeChatBoundaryCarriesActualStepsAndProofPath()
    {
        // Only the native-service boundary is mocked; the certificate was
        // generated by the real executor and projected by the real mapper.
        var (rule, proof) = Execute(7);
        Assert.True(LegendConnectCurriculumService.TryProjectScheduleCertificates(proof, [rule], out var certificates));
        var founderId = Guid.NewGuid().ToString("D");
        var priorFounder = Environment.GetEnvironmentVariable("FOUNDER_OID");
        Environment.SetEnvironmentVariable("FOUNDER_OID", founderId);
        try
        {
            await using var db = ControllerTestHelpers.BuildDb();
            db.AgentProfiles.Add(new AgentProfile
            {
                Id = Guid.NewGuid(), AgentUserId = founderId, AgentUpn = "certificate@legend.test",
                NormalizedEmail = "certificate@legend.test", IsActive = true
            });
            await db.SaveChangesAsync();
            ControllerTestHelpers.SeedGovernedLanguageBaseline(db, "en");
            var operations = new Mock<ILegendConnectOperations>(MockBehavior.Strict);
            operations.Setup(item => item.TryInferConversationWithDiscourseAsync(
                    "Show the governed allocation.", It.IsAny<IReadOnlyList<LegendConnectConversationContextItem>>(),
                    It.IsAny<LegendConnectDiscourseStateSnapshot?>(), It.IsAny<CancellationToken>(), "en",
                    It.IsAny<LegendConnectExternalProviderPolicy?>()))
                .ReturnsAsync(Native(proof, certificates));
            var configuration = new ConfigurationBuilder().Build();
            var factory = new NoExternalFactory();
            var profiles = new AgentProfileAccessResolver(db);
            var service = new LegendFounderAiConversationService(factory, configuration,
                new FounderLegendConnectService(operations.Object, profiles),
                NullLogger<LegendFounderAiConversationService>.Instance,
                new LegendFounderAiDiscourseStateService(db, profiles, operations.Object),
                new LegendLanguageRegistry(db, configuration), ControllerTestHelpers.BuildTranslationService());
            var response = await service.ReplyAsync(ControllerTestHelpers.BuildUser(founderId),
                new LegendFounderAiChatRequest
                {
                    Mode = "legend", NativeOnly = true, SourceLanguageCode = "en",
                    Messages = [new("user", "Show the governed allocation.")]
                });
            Assert.True(response.Succeeded, response.Error);
            Assert.Equal("native_response", response.Stage);
            Assert.Same(certificates, response.ScheduleCertificates);
            Assert.Equal(proof.TransitionPath, response.ReasoningTransitionPath);
            var wire = JsonSerializer.Deserialize<LegendFounderAiChatResponse>(JsonSerializer.Serialize(response));
            Assert.NotNull(wire);
            Assert.Equal(JsonSerializer.Serialize(certificates), JsonSerializer.Serialize(wire!.ScheduleCertificates));
            Assert.Equal(0, factory.Calls);
        }
        finally
        {
            Environment.SetEnvironmentVariable("FOUNDER_OID", priorFounder);
        }
    }

    private static LegendConnectNativeInferenceSnapshot Native(LegendGovernedReasoningProof proof,
        IReadOnlyList<LegendConnectGovernedScheduleCertificateSnapshot> certificates) =>
        new(true, 0m, "The governed allocation is available.", "semantic_transition_governed_composed",
            proof.EvidenceCount, "Executed homogeneous allocation proof.", false,
            "HigherStandard", "OriginalComposition", ScheduleCertificates: certificates,
            ReasoningTransitionPath: proof.TransitionPath);

    private static (LegendGovernedReasoningRule Rule, LegendGovernedReasoningProof Proof) Execute(int workload)
    {
        var source = new Dictionary<string, string>
        {
            ["units"] = "$schedule_workload", ["batch_size"] = "$schedule_batch_capacity",
            ["minutes"] = "$schedule_batch_duration", ["resources"] = "$schedule_available_resources",
            ["batch_resources"] = "$schedule_required_resources", ["deadline"] = "$schedule_time_limit"
        };
        var result = new Dictionary<string, string>
        {
            ["batches"] = "$schedule_batch_count", ["elapsed"] = "$schedule_elapsed",
            ["last_size"] = "$schedule_final_batch_size", ["status"] = "$schedule_status",
            ["allocation_digest"] = "$schedule_signature"
        };
        var rule = new LegendGovernedReasoningRule("batch-allocation", "reasoning.constrained-planning.batch",
            source, result, 3, 2, new HashSet<Guid> { Family }, new HashSet<Guid> { Family },
            ["first", "second", "third"], [new(Family, Family, false)]);
        var initial = new Dictionary<string, string>
        {
            ["units"] = workload.ToString(System.Globalization.CultureInfo.InvariantCulture), ["batch_size"] = "1",
            ["minutes"] = "1", ["resources"] = "2", ["batch_resources"] = "1", ["deadline"] = "1440"
        };
        return (rule, Assert.Single(LegendConnectGovernedReasoningExecutor.Derive(initial, [rule], [Family]).DerivedStates));
    }

    private sealed class NoExternalFactory : IHttpClientFactory
    {
        public int Calls { get; private set; }
        public HttpClient CreateClient(string name)
        {
            Calls++;
            throw new InvalidOperationException("Certificate propagation must not invoke an external provider.");
        }
    }
}
