using System.Text.Json.Serialization;

namespace Infrastructure.WebsiteEditing;

public static class WebsiteEditorSiteKeys
{
    public const string Protect = "protect";
    public const string Legend = "legend";
    public const string Business = "business";
    public const string GlobalOwnerKey = "__legend_global__";
    public const string BusinessOwnerPrefix = "business:";
    public const string ToolPrefix = "PublicWebsiteContent:";

    public static string BusinessOwnerKey(Guid businessId) =>
        BusinessOwnerPrefix + businessId.ToString("N");
}

public sealed record WebsiteEditorTicket(
    string SiteKey,
    string OwnerUserId,
    string? AgentSlug,
    bool IsFounder,
    DateTime ExpiresUtc,
    Guid? CommerceBusinessId = null,
    string? ActorUserId = null,
    string? ActorEmail = null,
    Guid? ActorClientProfileId = null);

public sealed class WebsiteStoreSettings
{
    public bool Enabled { get; set; }
    public string NavigationLabel { get; set; } = "Store";
    public string CartIcon { get; set; } = "cart";
    public int CartIconSizePx { get; set; } = 28;

    // Presentation only. Commerce action identity/destinations are generated by
    // the runtime and never stored in these editable records.
    public WebsiteControlPresentation StoreNavigation { get; set; } = new();
    public WebsiteControlPresentation CartNavigation { get; set; } = new();
}

public sealed class WebsiteControlPresentation
{
    public WebsiteVisualStyle Style { get; set; } = new();
    public Dictionary<string, WebsiteVisualStyle> BreakpointStyles { get; set; } = new(StringComparer.Ordinal);
    public WebsiteCompositionLayout Layout { get; set; } = new();
    public Dictionary<string, WebsiteCompositionLayout> BreakpointLayouts { get; set; } = new(StringComparer.Ordinal);
    public List<WebsiteAnimationBinding> Animations { get; set; } = new();
}

public sealed class WebsiteContentDocument
{
    [JsonExtensionData]
    public Dictionary<string, System.Text.Json.JsonElement>? UnexpectedFields { get; set; }

    public int Version { get; set; } = WebsiteStudioContract.CurrentDocumentVersion;
    public string? FaviconImageDataUrl { get; set; }
    public WebsiteStoreSettings Store { get; set; } = new();
    public List<WebsiteBreakpointDefinition> Breakpoints { get; set; } = WebsiteStudioContract.DefaultBreakpoints();

    // v3 has exactly one editable composition graph. Shared header/footer,
    // page bodies, and reusable components all use WebsiteCompositionNode.
    public WebsiteSharedShellDocument Shell { get; set; } = new();
    public Dictionary<string, WebsitePageDocument> Pages { get; set; } = new(StringComparer.Ordinal);
    public Dictionary<string, WebsiteReusableComponentDefinition> ReusableComponents { get; set; } = new(StringComparer.Ordinal);
    public Dictionary<string, WebsiteCollectionDefinition> Collections { get; set; } = new(StringComparer.Ordinal);
    public WebsiteDesignTheme Theme { get; set; } = new();
    public DateTime? UpdatedUtc { get; set; }

    // Read-only migration envelope. Never serialized into v3, never accepted by
    // save/publish, and removed immediately after the browser materializes v3.
    [JsonIgnore]
    internal LegacyWebsiteContentDocument? LegacyMigration { get; set; }
}

public sealed class WebsiteSharedShellDocument
{
    [JsonExtensionData]
    public Dictionary<string, System.Text.Json.JsonElement>? UnexpectedFields { get; set; }

    public List<WebsiteCompositionNode> Header { get; set; } = new();
    public List<WebsiteCompositionNode> Footer { get; set; } = new();
}

public sealed class WebsiteVisualStyle
{
    public string? TextAlign { get; set; }
    public decimal? FontScale { get; set; }
    public decimal? WidthPercent { get; set; }
    public decimal? PaddingTop { get; set; }
    public decimal? PaddingBottom { get; set; }
    public string? ObjectPosition { get; set; }
    public string? Color { get; set; }
    public string? BackgroundColor { get; set; }
    public string? FontFamily { get; set; }
    public int? FontWeight { get; set; }
    public decimal? FontSize { get; set; }
    public decimal? LineHeight { get; set; }
    public decimal? LetterSpacing { get; set; }
    public decimal? PaddingLeft { get; set; }
    public decimal? PaddingRight { get; set; }
    public decimal? BorderRadius { get; set; }
    public string? ObjectFit { get; set; }
    public decimal? HeightPx { get; set; }
    public decimal? OffsetXPercent { get; set; }
    public decimal? OffsetYPx { get; set; }
}

public sealed class WebsiteDesignTheme
{
    public string? Navy { get; set; }
    public string? NavyDeep { get; set; }
    public string? Gold { get; set; }
    public string? GoldStrong { get; set; }
    public string? Muted { get; set; }
    public string? Surface { get; set; }
    public string? Text { get; set; }
    public string? FontFamily { get; set; }
    public decimal? FontSize { get; set; }
    public decimal? BorderRadius { get; set; }
}


public static class WebsiteStudioContract
{
    public const int CurrentDocumentVersion = 3;

    public static List<WebsiteBreakpointDefinition> DefaultBreakpoints() =>
    [
        new() { Key = "mobile", Label = "Mobile", MinWidth = 0, MaxWidth = 767, IsSystem = true },
        new() { Key = "tablet", Label = "Tablet", MinWidth = 768, MaxWidth = 1199, IsSystem = true },
        new() { Key = "desktop", Label = "Desktop", MinWidth = 1200, MaxWidth = null, IsSystem = true }
    ];
}

public static class WebsiteCompositionSchema
{
    public static readonly IReadOnlyDictionary<string, IReadOnlyList<string>> AllowedTagsByType =
        new Dictionary<string, IReadOnlyList<string>>(StringComparer.Ordinal)
        {
            ["section"] = ["section"],
            ["container"] = ["div", "article", "header", "footer", "nav", "ul", "ol", "fieldset"],
            ["heading"] = ["h1", "h2", "h3", "h4", "h5", "h6"],
            ["text"] = ["p", "span", "small", "strong", "li", "label", "blockquote"],
            ["cta"] = ["a", "button"],
            ["link"] = ["a", "button"],
            ["image"] = ["img"],
            ["video"] = ["video"],
            ["form"] = ["form"],
            ["embed"] = ["div"],
            ["spacer"] = ["div"],
            ["reusable"] = ["div"]
        };

    public static bool IsAllowedType(string? type) =>
        !string.IsNullOrWhiteSpace(type) && AllowedTagsByType.ContainsKey(type.Trim().ToLowerInvariant());

    public static string? NormalizeTag(string? type, string? tag)
    {
        var key = (type ?? string.Empty).Trim().ToLowerInvariant();
        if (!AllowedTagsByType.TryGetValue(key, out var allowed) || allowed.Count == 0) return null;
        var candidate = (tag ?? string.Empty).Trim().ToLowerInvariant();
        return allowed.Contains(candidate, StringComparer.Ordinal) ? candidate : allowed[0];
    }

    public static string PromptGrammar() =>
        string.Join("\n", AllowedTagsByType.Select(pair =>
            $"- {pair.Key}: {string.Join(" | ", pair.Value)}"));
}


public sealed class WebsiteBreakpointDefinition
{
    public string Key { get; set; } = "";
    public string Label { get; set; } = "";
    public int MinWidth { get; set; }
    public int? MaxWidth { get; set; }
    public bool IsSystem { get; set; }
}

public sealed class WebsiteCompositionLayout
{
    public string Mode { get; set; } = "free";
    public string Direction { get; set; } = "column";
    public decimal? GapPx { get; set; }
    public int? Columns { get; set; }
    public decimal? MinItemWidthPx { get; set; }
    public string? AlignItems { get; set; }
    public string? JustifyContent { get; set; }
    public string? Wrap { get; set; }
}

public sealed class WebsiteAnimationBinding
{
    public string Id { get; set; } = Guid.NewGuid().ToString("N");
    public string Trigger { get; set; } = "view";
    public string Effect { get; set; } = "fade";
    public int DurationMs { get; set; } = 400;
    public int DelayMs { get; set; }
    public decimal? DistancePx { get; set; }
    public string Easing { get; set; } = "ease";
    public bool Once { get; set; } = true;
}

public sealed class WebsitePageNavigation
{
    public string? Label { get; set; }
    public bool ShowInNavigation { get; set; } = true;
    public string? ParentPath { get; set; }
    public int Order { get; set; }
    public bool IsDeleted { get; set; }
}

public sealed class WebsiteReusableComponentDefinition
{
    [JsonExtensionData]
    public Dictionary<string, System.Text.Json.JsonElement>? UnexpectedFields { get; set; }

    public string Id { get; set; } = Guid.NewGuid().ToString("N");
    public string Name { get; set; } = "";
    public string Kind { get; set; } = "section";
    public List<WebsiteCompositionNode> Composition { get; set; } = new();
}

public sealed class WebsiteCollectionDefinition
{
    public string Id { get; set; } = "";
    public string Name { get; set; } = "";
    public string Source { get; set; } = "business_facts";
    public List<string> Fields { get; set; } = new();
}

public sealed class WebsiteDataBinding
{
    public string CollectionId { get; set; } = "";
    public string Field { get; set; } = "";
    public string Target { get; set; } = "text";
}

public sealed class WebsiteDynamicPageBinding
{
    public string CollectionId { get; set; } = "";
    public string ItemKeyField { get; set; } = "";
    public string? RoutePattern { get; set; }
}
public sealed record BusinessWebsiteProfileSummary(
    Guid BusinessId,
    string BusinessName,
    string PreviewUrl,
    string? PrimaryDomain);

public sealed class WebsitePageDocument
{
    [JsonExtensionData]
    public Dictionary<string, System.Text.Json.JsonElement>? UnexpectedFields { get; set; }

    public string? Title { get; set; }
    public string? Description { get; set; }
    public WebsitePageNavigation Navigation { get; set; } = new();
    public WebsiteDynamicPageBinding? DynamicBinding { get; set; }

    // Server-owned runtime template binding. It is derived from site + canonical route,
    // never authored by GPT/Site Source. V3 still owns all allowed presentation.
    public string? SystemTemplateKey { get; set; }

    // The complete editable page body. There is no parallel template/mutation store.
    public List<WebsiteCompositionNode> Composition { get; set; } = new();
}

public sealed class WebsiteCompositionNode
{
    [JsonExtensionData]
    public Dictionary<string, System.Text.Json.JsonElement>? UnexpectedFields { get; set; }

    public string Id { get; set; } = Guid.NewGuid().ToString("N");
    public string Type { get; set; } = "text";
    public string? Tag { get; set; }
    public string? ClassName { get; set; }
    public string? Text { get; set; }
    public string? Title { get; set; }
    public string? ActionKey { get; set; }
    public string? Href { get; set; }
    public string? Target { get; set; }
    public string? Alt { get; set; }
    public Guid? MediaAssetId { get; set; }
    public string? MediaUrl { get; set; }
    public string? SystemKey { get; set; }
    public string? SystemBinding { get; set; }
    public string? SyncSourceId { get; set; }
    public bool? Hidden { get; set; }
    public List<WebsiteSignalBinding> Signals { get; set; } = new();
    public WebsiteVisualStyle Style { get; set; } = new();
    public Dictionary<string, WebsiteVisualStyle> BreakpointStyles { get; set; } = new(StringComparer.Ordinal);
    public WebsiteCompositionLayout Layout { get; set; } = new();
    public Dictionary<string, WebsiteCompositionLayout> BreakpointLayouts { get; set; } = new(StringComparer.Ordinal);
    public List<WebsiteAnimationBinding> Animations { get; set; } = new();
    public WebsiteDataBinding? DataBinding { get; set; }
    public List<WebsiteCompositionNode> Children { get; set; } = new();
}

public sealed class WebsiteNamedDraft
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Name { get; set; } = "";
    public string DocumentJson { get; set; } = "{}";
    public DateTime UpdatedUtc { get; set; } = DateTime.UtcNow;
}


public sealed record WebsiteCallToActionOption(
    string Key,
    string Group,
    string Label,
    string DefaultText,
    string Href,
    bool OpenInNewTab = false,
    string AnalyticsEventName = "cta_click",
    string? MetaIntentEventName = null,
    IReadOnlyList<string>? TextVariants = null,
    string BehaviorKey = "cta_click",
    string? RuntimeAction = null);

/// <summary>
/// One scope-aware CTA catalog for the shared LEGEND website editor. Dynamic contact
/// and booking actions are offered only when the existing scoped authority is configured.
/// </summary>
public static class WebsiteCallToActionCatalog
{
    private static readonly string[] HomeTexts =
        ["Home", "Go Home", "Back Home"];
    private static readonly string[] AboutTexts =
        ["About", "About Us", "Learn More", "Our Story", "Our Mission", "Who We Are"];
    private static readonly string[] ServicesTexts =
        ["Services", "View Services", "Our Services", "Explore Services", "See Services"];
    private static readonly string[] ContactTexts =
        ["Contact", "Contact Us", "Get in Touch", "Reach Out", "Let's Talk", "Talk to Us", "Speak With Us", "Send a Message", "Message Us"];
    private static readonly string[] QuoteTexts =
        ["Quote", "Free Quote", "Get a Quote", "Get a Free Quote", "Request a Quote", "Request a Free Quote", "Start a Quote", "Start My Quote", "Get My Quote"];
    private static readonly string[] CallTexts =
        ["Call", "Call Now", "Call Us", "Call Today", "Speak With Us", "Talk to Us", "Talk Now"];
    private static readonly string[] EmailTexts =
        ["Email", "Email Us", "Send Email", "Send an Email", "Message Us"];
    private static readonly string[] ScheduleTexts =
        ["Schedule", "Schedule Now", "Book Now", "Book a Call", "Schedule a Call", "Book a Meeting", "Schedule a Meeting", "Book an Appointment", "Schedule an Appointment", "Make an Appointment", "Reserve a Time", "Pick a Time"];
    private static readonly string[] ProtectionTexts =
        ["Protection", "Get Protected", "Protect What Matters", "Explore Protection", "Protection Options", "View Protection Options", "Learn About Protection"];

    public static IReadOnlyList<WebsiteCallToActionOption> Build(
        string siteKey,
        string? phone = null,
        string? email = null,
        string? bookingUrl = null,
        string? commerceStorePath = null)
    {
        var options = new List<WebsiteCallToActionOption>();
        void Add(
            string key,
            string group,
            string label,
            string defaultText,
            string? href,
            bool external = false,
            string analytics = "cta_click",
            IReadOnlyList<string>? textVariants = null,
            string behaviorKey = "cta_click",
            string? runtimeAction = null)
        {
            if (string.IsNullOrWhiteSpace(href) || href == "#") return;
            if (!Shared.Analytics.AnalyticsEventCatalog.TryGet(analytics, out var analyticsDefinition) ||
                !analyticsDefinition.AllowBrowser)
                throw new InvalidOperationException("CTA analytics must use the canonical browser event catalog.");
            if (!Shared.Analytics.AnalyticsEventCatalog.TryGetBehavior(behaviorKey, out var behavior) ||
                behavior.RequiresServerAuthority)
                throw new InvalidOperationException("Browser actions cannot claim a verified backend outcome.");
            // Provider names are projections of the canonical source contract.
            var metaIntent = Shared.Analytics.MetaSignalAnalyticsAliasCatalog.ResolveSignalName(analytics);

            var variants = new[] { defaultText }
                .Concat(textVariants ?? Array.Empty<string>())
                .Where(value => !string.IsNullOrWhiteSpace(value))
                .Select(value => value.Trim())
                .Distinct(StringComparer.Ordinal)
                .ToArray();
            options.Add(new(key, group, label, defaultText, href, external, analytics, metaIntent, variants, behavior.Key, runtimeAction));
        }

        if (siteKey == WebsiteEditorSiteKeys.Legend)
        {
            Add("legend_home", "Home", "Home", "Home", "/", textVariants: HomeTexts);
            Add("legend_about", "About", "About", "About", "/about", textVariants: AboutTexts);
            Add("legend_contact", "Contact", "Contact", "Contact", "/contact",
                textVariants: ContactTexts);
            Add("legend_protect", "Protection", "Protection", "Protection", "https://protect.mylegnd.com/", true,
                textVariants: ProtectionTexts);
        }
        else if (siteKey == WebsiteEditorSiteKeys.Protect)
        {
            Add("protect_home", "Home", "Home", "Home", "/", textVariants: HomeTexts);
            Add("protect_risk_assessment", "Assessment", "Risk assessment", "Start assessment", "/RiskAssessment", analytics: "risk_assessment_click");
            Add("protect_contact", "Contact", "Contact", "Contact", "/Contact",
                textVariants: ContactTexts);
            Add("protect_quote", "Quote", "Quote", "Quote", "/Quote",
                analytics: "quote_click", textVariants: QuoteTexts);
            foreach (var route in Shared.Analytics.ProtectRouteCatalog.Routes.Where(route => !string.IsNullOrWhiteSpace(route.QuoteType)))
            {
                var subject = route.DisplayName.Trim();
                Add(
                    "protect_" + route.PageKey,
                    "Quote · " + subject,
                    subject + " Quote",
                    subject + " Quote",
                    route.Path,
                    analytics: "quote_click",
                    textVariants:
                    [
                        subject + " Quote",
                        "Get a " + subject + " Quote",
                        "Get a Free " + subject + " Quote",
                        "Request a " + subject + " Quote",
                        "Start a " + subject + " Quote"
                    ]);
            }
            Add("protect_call", "Call", "Call", "Call", NormalizePhone(phone),
                textVariants: CallTexts);
            Add("protect_schedule", "Schedule", "Schedule", "Schedule", NormalizeHttps(bookingUrl), true,
                textVariants: ScheduleTexts);
        }
        else if (siteKey == WebsiteEditorSiteKeys.Business)
        {
            Add("business_home", "Home", "Home", "Home", "/", textVariants: HomeTexts);
            Add("business_about", "About", "About", "About", "/about", textVariants: AboutTexts);
            Add("business_services", "Services", "Services", "Services", "/services", textVariants: ServicesTexts);
            Add("business_contact", "Contact", "Contact", "Contact", "/contact",
                textVariants: ContactTexts);
            Add("business_quote", "Quote", "Quote", "Quote", "/contact",
                textVariants: QuoteTexts);
            Add("business_call", "Call", "Call", "Call", NormalizePhone(phone),
                textVariants: CallTexts);
            Add("business_email", "Email", "Email", "Email", NormalizeEmail(email),
                textVariants: EmailTexts);
            Add("business_schedule", "Schedule", "Schedule", "Schedule", NormalizeHttps(bookingUrl), true,
                textVariants: ScheduleTexts);
        }

        if (!string.IsNullOrWhiteSpace(commerceStorePath) &&
            WebsiteContentSanitizer.SanitizeUrl(commerceStorePath) is string storeRoot)
        {
            storeRoot = storeRoot.TrimEnd('/');
            Add("commerce_store", "Store", "View products", "View products", storeRoot);
            Add("commerce_cart", "Store", "View cart", "View cart", storeRoot + "/cart");
            Add("commerce_checkout", "Store", "Checkout / purchase flow", "Checkout", storeRoot + "/checkout");
            Add("commerce_add_to_cart", "Store", "Add current product to cart", "Add to cart", "#current-product", runtimeAction: "add_current_product");
        }
        Add("form_start", "Forms", "Start form", "Get started", "#website-form", runtimeAction: "focus_form");
        Add("submit", "Forms", "Submit form", "Submit", "#website-form", runtimeAction: "submit_form");
        return options;
    }

    public static bool TryResolveBehavior(string siteKey, string? actionKey, out Shared.Analytics.AnalyticsBehaviorContract behavior)
    {
        // Availability affects selection, not the identity of an already-published action.
        var option = Build(siteKey, "10000000000", "identity@example.invalid", "https://example.invalid/booking", "/store")
            .FirstOrDefault(candidate => string.Equals(candidate.Key, actionKey, StringComparison.Ordinal));
        if (option is not null) return Shared.Analytics.AnalyticsEventCatalog.TryGetBehavior(option.BehaviorKey, out behavior);
        behavior = null!;
        return false;
    }

    public static string? PrepareForPublish(
        WebsiteContentDocument document,
        IReadOnlyList<WebsiteCallToActionOption> options)
    {
        if (document.LegacyMigration is not null)
            return "This website must be materialized into the canonical v3 composition graph before publishing.";

        var byKey = options.ToDictionary(option => option.Key, StringComparer.Ordinal);

        string? ResolveComposition(WebsiteCompositionNode node)
        {
            if (!string.IsNullOrWhiteSpace(node.ActionKey))
            {
                if (!byKey.TryGetValue(node.ActionKey, out var option))
                    return "A configured button action is no longer available. Reopen the editor and choose an active action.";
                node.Href = option.Href;
                node.Target = option.OpenInNewTab ? "_blank" : "_self";
            }

            if (node.Type == "cta" &&
                string.IsNullOrWhiteSpace(node.ActionKey) &&
                (string.IsNullOrWhiteSpace(node.Href) || node.Href == "#" ||
                 WebsiteContentSanitizer.SanitizeUrl(node.Href) is null))
                return "Every CTA needs a canonical action or working custom destination before publishing.";

            if (node.Type == "form" &&
                !string.Equals(node.SystemKey, "canonical_inquiry", StringComparison.Ordinal))
                return "Website forms must use the canonical inquiry authority.";

            foreach (var child in node.Children)
            {
                var childError = ResolveComposition(child);
                if (childError is not null) return childError;
            }
            return null;
        }

        string? ResolveMany(IEnumerable<WebsiteCompositionNode> nodes)
        {
            foreach (var node in nodes ?? [])
            {
                var error = ResolveComposition(node);
                if (error is not null) return error;
            }
            return null;
        }

        var shellError = ResolveMany(document.Shell.Header) ?? ResolveMany(document.Shell.Footer);
        if (shellError is not null) return shellError;

        foreach (var page in document.Pages.Values)
        {
            var error = ResolveMany(page.Composition);
            if (error is not null) return error;
        }

        foreach (var component in document.ReusableComponents.Values)
        {
            var error = ResolveMany(component.Composition);
            if (error is not null) return error;
        }

        return null;
    }

    private static string? NormalizePhone(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        var trimmed = value.Trim();
        var digits = new string(trimmed.Where(char.IsDigit).ToArray());
        if (digits.Length < 7 || digits.Length > 15) return null;
        return "tel:" + (trimmed.StartsWith('+') ? "+" : "") + digits;
    }

    private static string? NormalizeEmail(string? value)
    {
        if (string.IsNullOrWhiteSpace(value) ||
            !System.Net.Mail.MailAddress.TryCreate(value.Trim(), out var address))
            return null;
        return "mailto:" + address.Address;
    }

    private static string? NormalizeHttps(string? value)
    {
        if (string.IsNullOrWhiteSpace(value) ||
            !Uri.TryCreate(value.Trim(), UriKind.Absolute, out var uri) ||
            uri.Scheme != Uri.UriSchemeHttps ||
            uri.UserInfo.Length != 0)
            return null;
        return uri.ToString();
    }
}
